# Задание №4. Отбор элементов транспортной сети {#lines-network-work}

**Цель задания** --- освоение методики отбора элементов транспортных сетей с использованием алгоритмов на графах

**Аннотация**. Задание посвящено знакомству с методикой автоматизированного отбора дорог для мелкомасштабного картографирования. Необходимо реализовать алгоритм прореживания транспортной сети (отбора линий), основанный  на принципе маршрутной связности населенных пунктов. Дополнительно реализуется расчет условной графической нагрузки для линий. Задание выполняется в среде _Model Builder_ __ArcGIS 10.5__ с модулем _Network Analyst_.

Предлагаемый для реализации алгоритм основан на предположении, что в результирующем масштабе необходимо показывать транспортные коммуникации, по которым проходят кратчайшие маршруты между соседними населенными пунктами. Понятие соседства при решении этой задачи может быть формализовано разоличными способами: по количеству [@krivosheina:2012], либо по смежности [@Schmid:2013wh]. В настоящей работе используется соседство по смежности: соседними считаются населенные пункты, у которых соприкасаются ячейки Вороного. Общая схема алгоритма выглядит следующим обазом:

1. Строится граф дорожной сети.
2. Строится диаграмма Вороного населенных пунктов.
3. Организуется цикл по точкам населенных пунктов:
    - выбирается текущая точка (_центральная_);
    - выбирается относящаяся к центральной точке ячейка Вороного;
    - для выбранной ячейки выбираются смежные с ней (касающиеся по границе);
    - выбираются соответствующие соседним ячейкам точки населенных пунктов;
    - от каждой соседней точки строится маршрут до центральной точки (решается задача _Closest Facility_)
    - линии, по которым прошли маршруты, помечаются флагом.
    
В результате выполнения алгоритма все транспортные коммуникации, которые оказались задействованы в кратчайших маршрутах, будут помечены специальным флагом. Генерализация завершается исключением непомеченных линий (физическое удаление не требуется, достаточно выполнить атрибутивный запрос).
    
## Часть 1. Подготовка исходных данных {-}

1. Добавьте в исходные слой линий целочисленное поле *Show*, которое будет заполняться флагом отбора.

2. Создайте набор пространственных объектов (**Feature Dataset**) внутри базы геоданных и импортируйте в него класс дорожной сети (_rdslin_).

3. Создайте в слое дорог новое целочисленное поле *Hierarchy* и заполните его значениями:
    - 1 — для автомагистралей и усовершенствованных шоссе
    - 2 — для шоссе
    - 3 — для всех прочих дорог

4. Внутри набора пространственных объектов создайте набор сетевых данных (*Network Dataset*), используя слой *rdslin*. Все параметры оставьте по умолчанию, за исключением:
    - *Elevation Fields* --- None
    - *Driving Directions* --- None
    - *Attributes*: добавить новый атрибут типа *Hierarchy* (**Add**). Далее добавить для него оценщика (**Evaluators**), указать, что оценку необходимо делать по полю **Hierarchy**.

## Часть 2. Создание моделей геообработки для отбора элементов транспортной сети {-}

Создайте внутреннюю модель геообработки **Road Selection Internal**. В качестве входных данных вводите 5 слоев:

 - исходные точки (**Input Points**),
 - слой диаграммы Вороного (**Input Thiessen Polygons**),
 - исходные линии (**Input Lines**),
 - набор сетевых данных (**Input Network Dataset**)
 - поле видимости (**Show Field**)
 
Реализуйте модель в соответствии со следующей последовательностью действий:

1. Итерировать выбор объектов в слое диаграммы Вороного (*Input Thiessen Polygons*).

2. Выбрать с помощью полигона 1 его соседей, используя правило BOUNDARY\_TOUCHES (**Select By Location**).

3. Выбрать точки соседей с помощью полигонов 2, используя правило INTERSECT (**Select By Location**).

4. Создать на основе сетевого набора данных слой поиска ближайших пунктов обслуживания (**Make Closest Facility Layer**). В качестве параметра *Number of Facilities to Find* оставьте 1. Установите режим движения TRAVEL\_FROM*.*

5. Добавить в слой поиска 4 точки соседей 3 (**Add Locations** в режиме *Incidents*)

6. Выбрать текущую точку с помощью полигона 1, используя правило WITHIN (**Select By Location**). Использовать в качестве предусловия результат 5.

7. Добавить в слой поиска текущую точку 6 (**Add Locations** в режиме *Facilities*).

8. Очистить выборку в слое диаграммы Вороного (*Input Thiessen Polygons*). (**Select By Attributes** в режиме CLEAR\_SELECTION). Использовать в качестве предусловия результат 7.

9. Очистить выборку в слое точек (*Input Points*). (**Select By Attributes** в режиме CLEAR\_SELECTION). Использовать в качестве предусловия результат 8.

10. Запустить расчет задачи *Closest Facility* для слоя 7 (**Solve**)

11. Извлечь линии маршрутов *Routes* (**Select Data**) из слоя 10.

12. Выбрать исходные линии (*Input Lines*) полученными маршрутами 11 (**Select By Location**), используя правило `SHARE_A_LINE_SEGMENT_WITH`.

13. Вычислить поле *Show Field* для выбранных линий, используя калькулятор поля (**Calculate Field**). Проставить выделенным линиям значение 1.

14. Очистить выборку в слое линий (Input Lines). (**Select By Attributes** в режиме `CLEAR_SELECTION`).

15. Удалить слой *Closest Facility* 4 (**Delete**). Использовать в качестве предусловия результат 14.

Создайте внешнюю модель геообработки **Road Selection**. В качестве входных слоев используйте:

 - исходные точки (**Input Points**);
 - исходные линии (**Input Lines**);
 - набор сетевых данных (**Input Network Dataset**);
 - поле видимости (**Show Field**).

Реализуйте модель в соответствии со следующей последовательностью действий:

1. Создать диаграмму Вороного точек (**Create Thiessen Polygons**). Разместите диаграмм в памяти компьютера (`in_memory\thiessen`)

2. Создать слой диаграммы Вороного (**Create Feature Layer**)

3. Вызвать модель геообработки **Road Selection Internal,** передав ей все входные слои + слой диаграммы Вороного.

## Часть 3. Создание модели геообработки для оценки относительной графической нагрузки по линейным объектам {-}

Используя имеющиеся у вас знания и навыки, создайте модель геообработки, которая будет давать оценку относительной графической нагрузки для линейных объектов по ячейкам регулярной сети.

**Относительная графическая нагрузка по линейным объектам** -- суммарная длина линий каждого класса (L~k~) с учетом весовых коэффициентов (w~k~), деленная на площадь ячейки (A):

$$\rho_{L} = \frac{\sum_{k}^{}{w_{k}L_{k}}}{A}$$
Числитель формулы имеет единицы измерения [на местности]{.underline} (км). Знаменатель выражен в единицах измерения [карты]{.underline} ($см^2$). Применительно к линейным объектам относительная графическая нагрузка является аналогом густоты, и также выражается в относительных единицах ($км/см^2$), но учитывает толщину линий в качестве весовых коэффициентов $w$, чтобы придать большую нагрузку ячейкам, где проходят линии высоких классов. Веса $w$ должны быть прямо пропорциональны толщинам линий (или равны им).

**Входные параметры:**

- Линейный слой
- Поле *Size Field*, отвечающее за графический вес линии (толщина линии в миллиметрах).
- Пространственное разрешение сетки (в сантиметрах изображения).
- Масштаб изображения

**Требования к результату:**

Результатом выполнения инструмента должен быть полигональный слой c ячейками регулярной сети, для каждой из которой в поле *Load* записана относительная графическая нагрузка, рассчитанная по вышеприведенной формуле.

**Указания к выполнению:**

В качестве отправной точки можно использовать модель геообработки для оценки относительной графической нагрузки точечных объектов, разработанную в Самостоятельной работе №3. В процессе экспериментальной работы используйте следующие толщины линий (в пикселах):

```{r}
rosstat::include_table('tables/linewidth_params.xlsx', caption = 'Параметры толщины линии')
```

## Часть 4. Создание и анализ карты транспортной связности районных центров субъекта {-}

Используя разработанные модели отбора и оценки графической нагрузки, выполните заключительную часть работы:

1. Выполните отбор элементов дорожной сети, проходящих через районные центры (poppnt\_dist). Оформите результат в виде карты масштаба 1:8 000 000. Используйте толщины линий 3, 1.5 и 0.75 пункта соответственно. На схеме должны быть подписаны все районные центры, нанесена граница субъекта и оформлена легенда по трем классам дорог.

2. Вычислите условную графическую нагрузку [всех]{.underline} исходных дорог в масштабе 1:1 000 000 (размер квадрата 2х2 см в масштабе карты). Используйте толщины линий 6, 3 и 1.5 пункта соответственно. Оформите картограмму графической нагрузки в масштабе 1:8 000 000.

3. Вычислите условную графическую нагрузку отобранных дорог в масштабе 1:8 000 000 (размер квадрата 2х2 см в масштабе карты). Используйте толщины линий 3, 1.5 и 0.75 пункта соответственно. Оформите картограмму графической нагрузки в масштабе 1:8 000 000.

4. Напишите отчет о проделанной работе, включающий:
    - Описание целей и задач самостоятельной работы
    - Описание идеи алгоритмов отбора элементов дорожной сети и оценки условной графической нагрузки для линейных объектов
    - Процесс создания моделей геообработки и их внешний вид
    - Процесс экспериментальной работы
    - Оценку полученных результатов с точки зрения географической достоверности. Оценка должна включать сравнение исходной и результирующей картины транспортной сети региона визуально и по картограмме условной графической нагрузки. 